apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: html-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/YOUR_USERNAME/YOUR_REPO.git
    targetRevision: HEAD
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: html-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
