apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: html-ingress
  namespace: html-app

spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: html-service
            port:
              number: 80
