apiVersion: v1
kind: Service

metadata:
  name: html-service
  namespace: html-app

spec:
  type: NodePort

  selector:
    app: html-app

  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
