name: DevSecOps GitOps Pipeline

on:
  push:

permissions:
  contents: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t vijaydevops769/html-app:${{ github.run_number }} ./html-project/app

    - name: Run Trivy Security Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: vijaydevops769/html-app:${{ github.run_number }}
        format: table

    - name: Push Docker Image
      run: |
        docker push vijaydevops769/html-app:${{ github.run_number }}

    - name: Update Kubernetes Deployment File
      run: |
        sed -i 's|image: .*|image: vijaydevops769/html-app:${{ github.run_number }}|g' html-project/k8s/deployment.yaml

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

        git add html-project/k8s/deployment.yaml

        git commit -m "Updated image to version ${{ github.run_number }}" || echo "No changes"

        git push
